= Messaging Library

image:https://travis-ci.org/container-mgmt/messaging-library.svg?branch=master["Build Status", link="https://travis-ci.org/container-mgmt/messaging-library"]
image:https://goreportcard.com/badge/container-mgmt/messaging-library["Go Report Card", link="https://goreportcard.com/report/github.com/container-mgmt/messaging-library"]
image:https://godoc.org/github.com/container-mgmt/messaging-library/pkg/client?status.svg["GoDoc", link="https://godoc.org/github.com/container-mgmt/messaging-library/pkg/client"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://opensource.org/licenses/Apache-2.0"]

This package provides a Go library that simplifies the implementation of
communication patterns, like request/reply, on top of a messaging broker
that supports queues and topics (destinations).

== Building

To build the project clone the repository to your go path and run the
`make` command.

To build the example `messaging-tool` and a testing broker `messaging-server`
run the `make binaries` command.

The `make binaries` command will install the binaries into `./.gopath/bin/` path
instead of `$GOPATH/bin` or `$GOBIN`, when executing the examples below use the
correct path (e.g. run `./.gopath/bin/messaging-server` if `./.gopath/bin` is not in
your `$PATH`).

=== Examples

==== List of examples

link:/cmd/messaging-tool/[messaging-tool] +
link:/cmd/messaging-server/[messaging-server]

==== Running

Run `messaging-server` testing Server:
``` Bash
$ messaging-server serve
```

Run `messaging-tool` testing tool, and wait for incoming messages:
``` Bash
$ messaging-tool receive --host 127.0.0.1 --destination "hello"
```

Run `messaging-tool` testing tool, and send a messages:
``` Bash
$ messaging-tool send --host 127.0.0.1 --destination "hello" --body "world"
```

== Usage

=== Publish a string message to a destination (queue or topic)

Example:
link:/cmd/messaging-tool/send.go[send.go]

[source,go]
----
import (
  ...

  // Import the message broker client interface.
  "github.com/container-mgmt/messaging-library/pkg/client"

  // Import a STOMP client implementation.
  "github.com/container-mgmt/messaging-library/pkg/connections/stomp"
)

...

  // Create a new connection object.
  var c client.Connection

  // Set a new STOMP connction to localhost:1888.
  c, err = stomp.NewConnection(&stomp.ConnectionBuilder{
    BrokerHost:   "lolcalhost",
    BrokerPort:   "1888",
  })
  err = c.Open()
  defer c.Close()

  // Make a message with plain text body "Hello subscriber.".
  m = client.Message{
    ContentType: "text/plain",
    Body:        "Hello subscriber.",
  }

  // Publish our hello message to the "destination name" destination.
  err = c.Publish(m, "destination name")
----

=== Subscribe to a destination (queue or topic)

Example:
link:/cmd/messaging-tool/receive.go[receive.go]



[source,go]
----
import (
  ...

  // Import the message broker client interface.
  "github.com/container-mgmt/messaging-library/pkg/client"

  // Import a STOMP client implementation.
  "github.com/container-mgmt/messaging-library/pkg/connections/stomp"
)

...

// We will use this function as a callback function for each new message
// published on specific destination.
func callback(m client.Message, destination string) (err error) {
	glog.Infof(
		"Received message from destination '%s':\n%s",
		destination,
		m.Body,
	)

	return
}

...

  // Create a new connection object.
  var c client.Connection

  // Set a new STOMP connction to localhost:1888.
  c, err = stomp.NewConnection(&stomp.ConnectionBuilder{
    BrokerHost:   "lolcalhost",
    BrokerPort:   "1888",
  })
  err = c.Open()
  defer c.Close()

  ...

  // Subscribe to the destination "destination name", and run callback function for each
  // new message.
  err = c.Subscribe("destination name", callback)
----
